version: '3'

services:
  balanceapi: 
    build:
      context: ./
      dockerfile: ./docker/balance.Dockerfile
    #platform: linux/amd64
    volumes:
      - .:/app
    ports:
      - 3003:3003
    environment:
      - KAFKA_URL=kafka:29092

      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=wallet
      - MYSQL_DATABASE_BALANCE=balance

      - MIGRATION_USERNAME=root
      - MIGRATION_PASSWORD=root
      - MIGRATION_HOSTNAME=mysql
      - MIGRATION_PORT=3306
      - MIGRATION_DB=mysql_wallet
      - MIGRATION_TABLE=migrations
    depends_on:
      mysql: 
        condition: service_healthy
      walletcore: 
        condition: service_healthy
    networks:
      - walletcore

  walletcore: 
    build:
      context: ./
      dockerfile: ./docker/walletcore.Dockerfile
    platform: linux/amd64
    environment:
      - KAFKA_URL=kafka:29092

      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=wallet
      - MYSQL_DATABASE_BALANCE=balance

      - MIGRATION_USERNAME=root
      - MIGRATION_PASSWORD=root
      - MIGRATION_HOSTNAME=mysql
      - MIGRATION_PORT=3306
      - MIGRATION_DB=mysql_wallet
      - MIGRATION_TABLE=migrations
    volumes:
      - .:/app
    depends_on:
      mysql: 
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - walletcore
    healthcheck:
      test: ["CMD", "curl", "-f", "--request", "POST", "http://localhost:8080/health"]
      interval: 3s
      timeout: 40s
      retries: 10

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_wallet
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    # volumes:
    #   - .docker/mysql90:/var/lib/mysql
    networks:
      - walletcore
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    

  zookeeper:
    image: "confluentinc/cp-zookeeper:latest"
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      TZ: Sao_Paulo/Brazil
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD", "echo", "mntr | nc 127.0.0.1 2181 | grep -q 'zk_server_state=leader'"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - walletcore

  kafka:
    image: "confluentinc/cp-enterprise-kafka:latest"
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy

    ports:
    # Exposes 9092 for external connections to the broker
    # Use kafka:29092 for connections internal on the docker network
    # See https://rmoff.net/2018/08/02/kafka-listeners-explained/ for details
      - '9092:9092'
    environment:
      TZ: Sao_Paulo/Brazil
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      CONFLUENT_METRICS_ENABLE: 'false'
    networks:
      - walletcore

  # control-center:
  #   image: confluentinc/cp-enterprise-control-center:7.3.0
  #   hostname: control-center
  #   container_name: control-center
  #   depends_on:
  #     - kafka
  #   ports:
  #     - "9021:9021"
  #   environment:
  #     CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:29092'
  #     CONTROL_CENTER_REPLICATION_FACTOR: 1
  #     CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
  #     CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
  #     CONFLUENT_METRICS_TOPIC_REPLICATION: 1
  #     PORT: 9021
  #   networks:
  #     - walletcore
  
networks:
  walletcore:
    driver: bridge