
POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "54964f6c-01f3-4207-85c6-4722022adf95",
    "account_id_to": "54964f6c-01f3-4207-85c6-8245b8467f2b",
    "amount": 2
}


POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json
{
    "name": "John Doe",
    "email": "john@j.com"
}

###

POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Vinicius Santos",
    "email": "vini@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "58fcf3ee-fb01-40e5-827f-4c470459d51b"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "a0e7206a-9705-4cdb-8ffc-9dbc11fb2e29",
    "account_id_to": "b42a154f-2569-46d6-b6fc-9bcc963bedc3",
    "amount": 1
}